// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeIRCNick(arg1) {
  return window['go']['main']['App']['ChangeIRCNick'](arg1);
}

export function CoinInfo() {
  return window['go']['main']['App']['CoinInfo']();
}

export function ConnectIRC() {
  return window['go']['main']['App']['ConnectIRC']();
}

export function ExecuteRPC(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRPC'](arg1, arg2);
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetBlockchainInfo() {
  return window['go']['main']['App']['GetBlockchainInfo']();
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetIRCMessages() {
  return window['go']['main']['App']['GetIRCMessages']();
}

export function GetIRCStatus() {
  return window['go']['main']['App']['GetIRCStatus']();
}

export function GetIRCUsers() {
  return window['go']['main']['App']['GetIRCUsers']();
}

export function GetNetworkTotals() {
  return window['go']['main']['App']['GetNetworkTotals']();
}

export function GetPeerCount() {
  return window['go']['main']['App']['GetPeerCount']();
}

export function GetPeerList() {
  return window['go']['main']['App']['GetPeerList']();
}

export function GetSyncProgress() {
  return window['go']['main']['App']['GetSyncProgress']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetWalletAddress() {
  return window['go']['main']['App']['GetWalletAddress']();
}

export function ListRPCMethods() {
  return window['go']['main']['App']['ListRPCMethods']();
}

export function RescanBlockchain() {
  return window['go']['main']['App']['RescanBlockchain']();
}

export function SendIRCMessage(arg1) {
  return window['go']['main']['App']['SendIRCMessage'](arg1);
}

export function SetMining(arg1) {
  return window['go']['main']['App']['SetMining'](arg1);
}
