// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoinInfo() {
  return window['go']['main']['App']['CoinInfo']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetBlockchainInfo() {
  return window['go']['main']['App']['GetBlockchainInfo']();
}

export function GetPeerCount() {
  return window['go']['main']['App']['GetPeerCount']();
}

export function GetSyncProgress() {
  return window['go']['main']['App']['GetSyncProgress']();
}

export function GetWalletAddress() {
  return window['go']['main']['App']['GetWalletAddress']();
}
