// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoinInfo():Promise<Record<string, any>>;

export function GetBalance():Promise<Record<string, any>>;

export function GetBlockchainInfo():Promise<Record<string, any>>;

export function GetPeerCount():Promise<number>;

export function GetSyncProgress():Promise<number>;

export function GetWalletAddress():Promise<string>;
