#!/usr/bin/env bash
# Extract coinparams constants for use in Makefile and CI.
# Source of truth: internal/coinparams/coinparams.go
#
# Usage (Makefile):  include coinparams.mk  (generated by this script)
# Usage (CI):        eval $(bash scripts/coinparams.sh --env)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COINPARAMS="${SCRIPT_DIR}/../internal/coinparams/coinparams.go"

if [ ! -f "$COINPARAMS" ]; then
    echo "ERROR: coinparams.go not found at $COINPARAMS" >&2
    exit 1
fi

extract() {
    grep -E "^\s+$1\s*=" "$COINPARAMS" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/'
}

COIN_NAME="$(extract Name)"
COIN_NAME_LOWER="$(extract NameLower)"
DAEMON_NAME="$(extract DaemonName)"
CLI_NAME="$(extract CLIName)"
GENESIS_NAME="$(extract GenesisToolName)"
ADVERSARY_NAME="$(extract AdversaryToolName)"
GUI_NAME="$(extract GUIName)"
DATA_DIR_NAME="$(extract DefaultDataDirName)"
CONF_FILE_NAME="$(extract ConfFileName)"
COPYRIGHT="$(extract CopyrightHolder)"

if [ "${1:-}" = "--env" ]; then
    # Shell-compatible export statements for CI.
    echo "export COIN_NAME=\"$COIN_NAME\""
    echo "export COIN_NAME_LOWER=\"$COIN_NAME_LOWER\""
    echo "export DAEMON_NAME=\"$DAEMON_NAME\""
    echo "export CLI_NAME=\"$CLI_NAME\""
    echo "export GENESIS_NAME=\"$GENESIS_NAME\""
    echo "export ADVERSARY_NAME=\"$ADVERSARY_NAME\""
    echo "export GUI_NAME=\"$GUI_NAME\""
    echo "export DATA_DIR_NAME=\"$DATA_DIR_NAME\""
    echo "export CONF_FILE_NAME=\"$CONF_FILE_NAME\""
    echo "export COPYRIGHT=\"$COPYRIGHT\""
else
    # Makefile-compatible variable assignments (for include).
    echo "COIN_NAME := $COIN_NAME"
    echo "COIN_NAME_LOWER := $COIN_NAME_LOWER"
    echo "DAEMON_NAME := $DAEMON_NAME"
    echo "CLI_NAME := $CLI_NAME"
    echo "GENESIS_NAME := $GENESIS_NAME"
    echo "ADVERSARY_NAME := $ADVERSARY_NAME"
    echo "GUI_NAME := $GUI_NAME"
    echo "DATA_DIR_NAME := $DATA_DIR_NAME"
    echo "CONF_FILE_NAME := $CONF_FILE_NAME"
    echo "COPYRIGHT := $COPYRIGHT"
fi
